// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJuEld2idfW1J1g41N-HGO-YlooBZ3slM',
    appId: '1:940901639729:web:45c4d8c29b4476cf93d710',
    messagingSenderId: '940901639729',
    projectId: 'learn-with-ai-91b91',
    authDomain: 'learn-with-ai-91b91.firebaseapp.com',
    storageBucket: 'learn-with-ai-91b91.appspot.com',
    measurementId: 'G-3D1M8FM065',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-8JWwkMML8E4H_XWnyE3jeQlRe98BoH4',
    appId: '1:940901639729:android:3cc567c4e9b9a36293d710',
    messagingSenderId: '940901639729',
    projectId: 'learn-with-ai-91b91',
    storageBucket: 'learn-with-ai-91b91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnXaEkggl3nUMrtCpyrYZ-94dkvdiGkRU',
    appId: '1:940901639729:ios:bd8788bb5bda436593d710',
    messagingSenderId: '940901639729',
    projectId: 'learn-with-ai-91b91',
    storageBucket: 'learn-with-ai-91b91.appspot.com',
    iosBundleId: 'com.example.learnWithAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnXaEkggl3nUMrtCpyrYZ-94dkvdiGkRU',
    appId: '1:940901639729:ios:e3d5f77e940b7b7a93d710',
    messagingSenderId: '940901639729',
    projectId: 'learn-with-ai-91b91',
    storageBucket: 'learn-with-ai-91b91.appspot.com',
    iosBundleId: 'com.example.learnWithAi.RunnerTests',
  );
}
